/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ifvgjmtryvcqsqmqzuvn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmdmdqbXRyeXZjcXNxbXF6dXZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NjE2NDAsImV4cCI6MjA4ODMzNzY0MH0.dhQlSFG_g1Uk-TMlSopYXivazlWrPmPfUj-_kH9v-Wg"